### ISSUE TITLE
can't add screenshot

### ISSUE THREAD

**Issue by hairy-tortoise** [millsteed/hookshot#1]
![Screenshot_20230807-015537_1](https://github.com/millsteed/hookshot/assets/82129596/a4b5551d-b71a-4156-8d18-558bb4e04355)

**Comment by millsteed** [comment]
Thanks @hairy-tortoise, this is fixed in https://github.com/millsteed/hookshot/commit/f03f1ad49945d7ed1af9ad051fa7be46d8877c08.
